common:
  job_name: "fedavg_cifar10_homo"
  server_url: "localhost:9200"
  random_seed: 0
  client_num: 4
  log_output_path: "./log"
  device: "cuda"

model:
  model: "resnet18"

data:
  dataset: "CIFAR10"
  data_cache_dir: "./data"
  partition_method: "homo"
  partition_alpha: 1.0

train:
  round: 30
  batch_size: 100
  inner_loop: 100
  learning_rate: 0.1
  weight_decay: 0.01
