# common
repo_name: "fedavg_cifar10_hetero1.0"
server_url: "localhost:9200"
random_seed: 0
worker_num: 4
log_output_path: "./log"
device: "cuda"

# data:
data_cache_dir: "./data"
partition_method: "hetero"
partition_alpha: 1.0

# train
round: 30
batch_size: 100
inner_loop: 100
